### ISSUE TITLE
Basic Plan

### ISSUE THREAD

**Issue by AleCandido** [AleCandido/quad#1]
- [x] implement non-adaptive rectangles/trapezoid #2
- [x] return integration error #3
- [x] implement `vec` with a simple criterion #4
- [x] bind for Python
- [x] benchmark against non-simultaneous and `scipy.quad_vec` #5
